export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PUDO_SAVED_ADDRESSES_SUCCESS = 'LOAD_PUDO_SAVED_ADDRESSES_SUCCESS';
export const GET_PUDO_COLLECTION_POINTS_SUCCESS = 'GET_PUDO_COLLECTION_POINTS_SUCCESS';
export const UPDATE_PUDO_CURRENT_POSITION_SUCCESS = 'UPDATE_PUDO_CURRENT_POSITION_SUCCESS';
export const UPDATE_PUDO_COLLECTION_POINTS_SUCCESS = 'GET_PUDO_COLLECTION_POINTS_SUCCESS';

export const ACTIVATE_ADD_COLLECTION_POINT_SUCESS = 'ACTIVATE_ADD_COLLECTION_POINT_SUCCESS';
export const DEACTIVATE_ADD_COLLECTION_POINT_SUCCESS = 'DEACTIVATE_ADD_COLLECTION_POINT_SUCCESS';

export const ENTER_COLLECTION_POINT = 'ENTER_COLLECTION_POINT';
export const LEAVE_COLLECTION_POINT = 'LEAVE_COLLECTION_POINT';

export const ACTIVATE_DISPLAY_COLLECTION_POINT_INFO_SUCCESS = "ACTIVATE_DISPLAY_COLLECTION_POINT_INFO_SUCCESS";
export const DEACTIVATE_DISPLAY_COLLECTION_POINT_INFO_SUCCESS = "DEACTIVATE_DISPLAY_COLLECTION_POINT_INFO_SUCCESS";
export const DISPLAY_COLLECTION_POINT_SUCCESS = 'DISPLAY_COLLECTION_POINT_SUCCESS';


