export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PUDO_SAVED_ADDRESSES_SUCCESS = 'LOAD_PUDO_SAVED_ADDRESSES_SUCCESS';
export const GET_PUDO_CURRENT_POSITION_SUCCESS = 'GET_PUDO_CURRENT_POSITION_SUCCESS';
export const GET_PUDO_COLLECTION_POINTS_SUCCESS = 'GET_PUDO_COLLECTION_POINTS_SUCCESS';
