export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PUDO_SAVED_ADDRESSES_SUCCESS = 'LOAD_PUDO_SAVED_ADDRESSES_SUCCESS';
export const GET_PUDO_CURRENT_POSITION_SUCCESS = 'GET_PUDO_CURRENT_POSITION_SUCCESS';
export const GET_PUDO_COLLECTION_POINTS_SUCCESS = 'GET_PUDO_COLLECTION_POINTS_SUCCESS';
export const ACTIVATE_ADD_COLLECTION_POINT = 'ACTIVATE_ADD_COLLECTION_POINT';
export const DEACTIVATE_ADD_COLLECTION_POINT = 'DEACTIVATE_ADD_COLLECTION_POINT';
export const ACTIVATE_COLLECTION_POINT_INFO = 'ACTIVATE_COLLECTION_POINT_INFO';
export const DEACTIVATE_COLLECTION_POINT_INFO = 'DEACTIVATE_COLLECTION_POINT_INFO';
export const SELECT_COLLECTION_POINT_SUCCESS = 'SELECT_COLLECTION_POINT_SUCCESS';
